//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TimDuongEntities : DbContext
    {
        public TimDuongEntities()
            : base("name=TimDuongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Phong> Phongs { get; set; }
    
        public virtual ObjectResult<string> Tim(string tuKhoa)
        {
            var tuKhoaParameter = tuKhoa != null ?
                new ObjectParameter("tuKhoa", tuKhoa) :
                new ObjectParameter("tuKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Tim", tuKhoaParameter);
        }
    }
}
